#!/usr/bin/bash


<<Installer
This File is Installer For KYGnus_Backup App.
we install Clamav and RKhunter and Maldet for Scan.
if You use Fedora(35) like Me, it Might be not have Crontab Installed Default
Installer


install_and_config_av(){
	linux=$(cat /etc/os-release | grep -w "NAME=.*")
		if [ "$linux" == "NAME=Fedora" ];then 
		echo $(yum install clamav clamd)
		echo $(/usr/bin/freshclam -v)  #for updating freshclam databases
		echo $(touch /var/log/freshclam.log)
		echo $(chmod 600 /var/log/freshclam.log)
		echo $(chown clamav /var/log/freshclam.log)
		#Recomended Set This Config For Server : 3 * * * * /usr/bin/freshclam --quiet
		echo "I Recomend You Set This Config for Server in crontab:3 * * * * /usr/bin/freshclam --quiet"
		echo "I Recomend You Set Clamav Scan To Crontab service To Scan System in Certain Times"

		elif [ "$linux" == "NAME=Ubuntu" ];then
			echo $(sudo apt-get install clamav clamav-daemon)
			echo $( sudo systemctl stop clamav-freshclam)
			echo $(sudo freshclam)
			echo "if sudo freshclam worked for your system?(yes/no)"
			read fresponse
			if [ "$fresponse" == yes ];then
				echo "OK"
			elif [ "$fresponse" == no ];then
				echo $(sudo mkdir /var/lib/clamav)
				echo $(cp daily.cvd /var/lib/clamav/daily.cvd)
				echo $(sudo systemctl start clamav-freshclam)
			fi
		elif [ "$linux" == "Alpine Linux" ];then
			echo $(sudo apt-get install clamav clamav-daemon)
			echo $( sudo systemctl stop clamav-freshclam)
			echo $(sudo freshclam)
			echo "if sudo freshclam worked for your system?(yes/no)"
			read fresponse
			if [ "$fresponse" == yes ];then
				echo "OK"
			elif [ "$fresponse" == no ];then
				echo $(sudo mkdir /var/lib/clamav)
				echo $(cp daily.cvd /var/lib/clamav/daily.cvd)
				echo $(sudo systemctl start clamav-freshclam)
			fi

		elif [ "$linux" == "Rocky Linux-" ];then
			echo $(yum install clamav clamd)
			echo $(/usr/bin/freshclam -v)  #for updating freshclam databases
			echo $(touch /var/log/freshclam.log)
			echo $(chmod 600 /var/log/freshclam.log)
			echo $(chown clamav /var/log/freshclam.log)
			#Recomended Set This Config For Server : 3 * * * * /usr/bin/freshclam --quiet
			echo "I Recomend You Set This Config for Server in crontab:3 * * * * /usr/bin/freshclam --quiet"
			echo "I Recomend You Set Clamav Scan To Crontab service To Scan System in Certain Times"

		fi
}

install_and_config_rootkit_hunter(){
	echo $(cd /tmp)
	echo $(wget http://downloads.sourceforge.net/project/rkhunter/rkhunter/1.4.6/rkhunter-1.4.6.tar.gz)
	echo $(tar -xvf rkhunter-1.4.6.tar.gz)
	echo $(cd rkhunter-1.4.6)
	echo $(./installer.sh --install)
}



install_and_config_malware_detect(){
	echo $(cd /usr/local/src)
	echo $(wget http://www.rfxn.com/downloads/maldetect-current.tar.gz)
	echo $(cd malwaredetect-1.5)
	echo $(./install.sh)
	echo "quarantine_hits = "1" >> /usr/local/maldetect/conf.maldet"
}






