#!/usr/bin/bash



username=$(whoami) # Get username of system

<<check_directory

This part of code check if KYGnus_Backup directory
is created or if not created Create New One

check_directory


KYGnus_dir=/home/$username/KYGnus_Backup
if test -d "$KYGnus_dir"; then
	    echo "$KYGnus_dir exists."
    else
	    mkdir /home/$username/KYGnus_Backup
fi

Directory="/home/koosha/Documents/testfiles/RUST"



time=$(date +%H%M) # Get Time of system in Hour and Minute 
disk=$(du -sh $Directory) # check Usage of Directory



<<Scan

this Part of code check Directory for malicious Files and 
Scan it with Linux popular Security Tools like clamav and RKhunter

Scan

scan(){

	clamav_scan=$(clamscan -s $Directory) # Scan
	clamav_move=$(clamscan -r --move $Directory) # Remove
	maldet=$(maldet -a $Directory) # Detect malware
	maldet_monitor=$(maldet --monitor $Directory) # show what scanned
	maldet_report=$(maldet --report) # show result of scan
	rkhuner=$(rkhunter -c) # Scan for Rootkit
}


<<first_backup
for First Time app Get backup fir name 1 and Calculate sha256sum Directory
and save them
first_backup


first(){
	if [ "$time" = 2053 ];then
		echo "Started First Backup..."
		first_backup=$(tar cfvz $KYGnus_dir/1_backup.tar.gz $Directory)
		echo $first_backup
		echo "Start Calculate sha256um of Files in $Directory"
		hash_first=$(find $Directory -type f -exec sha256sum {} \; > $KYGnus_dir/sha256sum )
		echo "sha256sum Files are Calculated" > Backup.txt
		echo $hash_first


	fi

}

first

<<second_backup
at this Part system check Directory in special Time and
id get difference Between last backup and this ,get new One
with name 2
second_backup


second(){
	if [ "$time" = 2054 ];then
		ff=$(find $KYgnus_dir -type f -iname "1_backup.tar.gz")
		sha_s=$(find $Directory -type f -exec sha256sum {} \;)
		if [ "$ff" ];then
			dusage=$(du -sh $Directory)
			if [ "$dusage" = "$disk" ];then
				echo "No Detected File Changing"
			else

				echo "Start New Backup"
				scan
				tar cfvz 2_backup.tar.gz $Directory
			fi
		else
			echo "Error:First Not Detected First BAckup"
		fi
	fi


}


second








